#!/bin/bash
# dotfiles installer — /setup 스킬 안내 래퍼
echo "=== dotfiles ==="
echo ""
echo "권장: Claude Code에서 /setup 실행"
echo "  cd ~/dotfiles && claude"
echo "  → /setup"
echo ""
echo "Claude Code 없이 수동 설치하려면:"
echo "  bash templates/ai/claude/skills/setup/scripts/check-env.sh"
echo "  bash templates/ai/claude/skills/setup/scripts/init-config.sh"
echo "  bash templates/ai/claude/skills/setup/scripts/link-tool.sh claude"
echo "  bash templates/ai/claude/skills/setup/scripts/link-shell.sh zsh"
echo "  bash templates/ai/claude/skills/setup/scripts/verify.sh"
echo ""
